config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {invitations: 'users_invitations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :articles
  resources :tutees_profiles
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
  validates :title, presence: true, length: {maximun:100,minimum:6}
  validates :description, presence: true
  validates :user_id, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  # validates_presence_of :full_name
  has_many :articles



  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        full_name: auth.info.first_name,
        password: Devise.friendly_token[0, 20]
      )
    end

    user
  end

  def self.new_with_session(params, session)
   super.tap do |user|
     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
       user.email = data["email"] if user.email.blank?
     end
   end
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permited_parameters, if: :devise_controller?

  def configure_permited_parameters
  	devise_parameter_sanitizer.permit(:sign_up) do |user_params|
  		user_params.permit(:full_name,
  											 :email,
  											 :password,
  											 :password_confirmation)
  	end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit,:update, :show, :destroy]

  def index
    @article=Article.all
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      flash[:notice] = "Article was successfully created."
      redirect_to article_path(@article)
    else
        render 'new'
    end
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article successfully updated."
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @article.destroy

    flash[:notice] = "Article was successfully deleted"
    redirect_to articles_path
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  # def twitter
  #   callback_from :twitter
  # end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => provider.capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_invitations_controller.rb
class UsersInvitationsController < Devise::InvitationsController
	def edit
		render :edit
	end
	def update
		self.resource = resource_class.accept_invitation!(resource_params)
		if resource.errors.empty?
      flash_message = resource.active_for_authentication? ? :updated : :updated_not_active                                                                                        
      set_flash_message :notice, flash_message
      sign_in(resource_name, resource)

      redirect_to 'root_path', :alert => "Welcome! Please fill out your profile and upload a headshot." 
    else
      respond_with_navigational(resource){ render :edit, :layout => false }
    end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to articles_path(@article)
    end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commments_helper.rb
module CommmentsHelper
end

app/helpers/users_invitations_helper.rb
module UsersInvitationsHelper
end

app/views/admin/users/new_invitation.html.erb
<h2>Send invitation</h2>

<%= form_for @user, :url => send_invitation_admin_users_path do |f| %>
   
   <table style='width: 50%'>
   	<tr>
   		<td><%= f.label :email %></td>
   		<td><%= f.text_field :email, :required => true %></td>
   	</tr>
   </table>
   
  <%= f.submit  "Send an Invitation" %>
<% end %>

app/views/articles/_form.html.erb
<%if @article.errors.any?%>
    <h2>The following errors prevented the article from getting created.</h2>
    <ul>
      <%@article.errors.full_messages.each do |msg|%>
        <li>
          <%=msg%>
      </li>
      <%end%>
    </ul>
<%end%>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <fieldset>
        <%= form_for @article do |f|%>
        <div class="form-group">
          <%= f.label :title%>
          <%= f.text_field :title,class: "form-control", placeholder: "Title"%>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description,size: "30x10",class: "form-control", placeholder: "Description"%>
        </div>
          <%= f.submit class:"btn btn-default"%>
          <%= link_to 'All articles list',articles_path(@article),class:"btn btn-info"%>
      <%end%>
    </fieldset>
  </div>
</div>

</div>

app/views/articles/edit.html.erb
<div class="container">
<h3>Edit article</h3>
<%= link_to 'create article',new_article_path, class:"btn btn-primary"%>
</div>
<%=render 'form'%>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">

      <h3>Articles</h3>
      <%if user_signed_in?%>
      <%= link_to 'create article',new_article_path, class: "btn btn-primary"%>
      <%end%>
      <% @article.each do |article|%>
        <article class="article-block">
          <div class="row">
            <div class="col-md-12">
              <div class="row">
                <div class="col-md-12">
                  <div class="article-main">
                    <h3><%= article.title%></h3>
                    <p><%= article.description%></p>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <%if article.user.full_name.nil?%>
                    <small>Created by: Unknown</small>
                  <%else%>
                    <small>Created by: <%= article.user.full_name%></small>
                  <%end%> |
                    <small>Created at:<%= time_ago_in_words(article.created_at)%></small> |
                    <small>Updated by:<%= time_ago_in_words(article.updated_at) %></small>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="article-control pull-right">
                    <ul>
                      <!-- <li><%= link_to 'Show',article_path(article),class: "btn btn-info"%></li> -->
                      <%if article.user == current_user%>
                      <li> <%= link_to 'Edit',edit_article_path(article),class: "btn btn-info"%></li>
                      <li><%= button_to 'Delete', article_path(article),class: "btn btn-danger", method: :delete, action: :destroy,  onclick: 'return confirm("Are you sure?")'%></li>
                    </ul>
                    <%end%>
                  </div>
                </div>
              </div>
            </div>
            </div>
          </article>
      <%end%>
      </div>
    </div>
  </div>
</div

app/views/articles/new.html.erb
<div class="container">
<h3>Create a new article</h3>
</div>
<%=render 'form'%>

app/views/articles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">

      <h3>Articles</h3>
      <%if user_signed_in?%>
      <%= link_to 'create article',new_article_path, class: "btn btn-primary"%>
      <%end%>
        <article class="article-block">
          <div class="row">
            <div class="col-md-12">
              <div class="row">
                <div class="col-md-12">
                  <div class="article-main">
                    <h3><%= @article.title%></h3>
                    <p><%= @article.description%></p>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <%if @article.user.full_name.nil?%>
                    <small>Created by: Unknown</small>
                  <%else%>
                    <small>Created by: <%= @article.user.full_name%></small>
                  <%end%> |
                    <small>Created at:<%= time_ago_in_words(@article.created_at)%></small> |
                    <small>Updated by:<%= time_ago_in_words(@article.updated_at) %></small>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="article-control pull-right">
                    <ul>

                      <%if @article.user == current_user%>
                      <li> <%= link_to 'All articles',articles_path(@article),class: "btn btn-info"%></li>
                      <li> <%= link_to 'Edit',edit_article_path(@article),class: "btn btn-info"%></li>
                      <li><%= button_to 'Delete', article_path(@article),class: "btn btn-danger", method: :delete, action: :destroy,  onclick: 'return confirm("Are you sure?")'%></li>
                    </ul>
                    <%end%>
                  </div>
                </div>
              </div>
            </div>
            </div>
          </article>
        <%= render partial: "comments/comments", locals: {commentable: @article}%>
      </div>
  </div>
</div

app/views/layouts/_messages.html.erb
<%flash.each do |name,msg|%>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 message">
      <ul>
        <li>
          <%= msg%>
        </li>
      </ul>
    </div>
  </div>
</div>
<%end%>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%=link_to 'Ten Fingers', root_path, class:"navbar-brand",id:"logo"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav pull-right" id="menu">
        <li><%=link_to 'Articles', articles_path%></li>
        <%if user_signed_in?%>
          <li><%=link_to 'Logout', destroy_user_session_path,method: :delete%></li>
          <li><%= current_user.full_name.present? ? current_user.full_name.titleize : 'Unkonwn'%>
          <% else %>
            <li><%=link_to 'Login', new_user_session_path%></li>
            <li><%=link_to 'Sign up',  new_user_registration_path%></li>
            <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path %>
          <%end%>
      </ul>
      <!-- <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <%= render 'layouts/messages'%>
    <div class="container-fluid">
          <%= yield %>
    </div>
  </body>
</html>

app/views/users/invitations/edit.html.erb
<h2><%= t 'devise.invitations.edit.header' %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => { :method => :put } do |f| %>
  <%= devise_error_messages! %>
  <%= f.hidden_field :invitation_token %>

  <% if f.object.class.require_password_on_accepting %>
  <p><%= f.label :password %><br />
  <%= f.password_field :password %></p>

  <p><%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %></p>
  <% end %>

  <p><%= f.submit t("devise.invitations.edit.submit_button") %></p>
<% end %>

app/views/users/invitations/new.html.erb
<h2><%= t "devise.invitations.new.header" %></h2>

<%= form_for resource, :as => resource_name, :url => invitation_path(resource_name), :html => {:method => :post} do |f| %>
  <%= devise_error_messages! %>

<% resource.class.invite_key_fields.each do |field| -%>
  <p><%= f.label field %><br />
  <%= f.text_field field %></p>
<% end -%>

  <p><%= f.submit t("devise.invitations.new.submit_button") %></p>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div class="l-welcome">
  <div class="container">
    <div class="col-md-12" id="welcome">
      <h1>Welcome to the Ten Fingers</h1>
    </div>
  </div>
</div>